# Generated by Django 4.2.29 on 2026-03-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to='fee_slips/'),
        ),
    ]
