# Generated by Django 4.2.29 on 2026-03-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_feepayment_slip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='slip_image',
        ),
    ]
