# Generated by Django 4.2.29 on 2026-03-19 13:09

from django.db import migrations, models
import hostel_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_remove_feepayment_slip_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='slip_image',
            field=models.ImageField(blank=True, null=True, upload_to=hostel_app.models.slip_upload_path),
        ),
    ]
