# Generated by Django 5.1.7 on 2026-03-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_feepayment_slip_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomallocation',
            options={},
        ),
    ]
