# Generated by Django 5.1.7 on 2026-05-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_alter_roomallocation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomallocation',
            options={'ordering': ['-created_at']},
        ),
    ]
