# Generated by Django 5.1.7 on 2026-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_alter_roomallocation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='aadhar_back',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='aadhar_front',
            field=models.FileField(blank=True, null=True, upload_to='documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='income_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/income/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jeep_rank_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/jeep/'),
        ),
    ]
