# Generated by Django 5.1.7 on 2026-05-02 12:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_studentprofile_aadhar_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='aadhar_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhar_back'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='aadhar_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='aadhar_front'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='income_certificate',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='income_certificate'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='jeep_rank_card',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='jeep_rank_card'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Profile Photo'),
        ),
    ]
